name: Keep DB Alive

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  Keep-DB-Alive:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Ping It
        uses: fjogeleit/http-request-action@v1.14.0
        with:
          url: '${{ secrets.db_url }}'
          method: 'GET'
          customHeaders: '{"apikey": ${{ secrets.db_apiKey }}}'
